/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 .\public\models\lotusEmira.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useSelector } from 'react-redux';
import { MeshStandardMaterial } from 'three';

export function LotusEmira(props) {
    const cbc = useSelector((state) => state.carColors.carBodyColor);
    const inc = useSelector((state) => state.carColors.InteriorColor);
    const rim = useSelector((state) => state.carColors.rimColor);
    const rimType = useSelector((state) => state.carColors.rimType);
    const carBodyColor = new MeshStandardMaterial({ color: cbc });
    const interiorColor = new MeshStandardMaterial({ color: inc });
    const rimColor = new MeshStandardMaterial({ color: rim });
    const { nodes, materials } = useGLTF('./models/lotusEmira.glb')
    const nodes1 = useGLTF('./models/wheelRims.glb').nodes

    return (
        <group {...props} dispose={null}>
            <group position={[4.781, -0.489, 1.527]} scale={0.167}>
                <group rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh geometry={nodes.Object_2.geometry} material={materials.Fari0051Mtl} />
                    <mesh geometry={nodes.Object_3.geometry} material={materials.Wind0011Mtl} />
                    <mesh geometry={nodes.Object_4.geometry} material={materials.Wind1Mtl} />
                    <mesh geometry={nodes.Object_5.geometry} material={materials.Boot0051Mtl} />
                    <mesh geometry={nodes.Object_6.geometry} material={materials.Boot1Mtl} />
                    <mesh geometry={nodes.Object_7.geometry} material={materials.Bumperr0061Mtl} />
                    <mesh geometry={nodes.Object_8.geometry} material={materials.Bumperr1Mtl} />
                    <mesh geometry={nodes.Object_9.geometry} material={carBodyColor} />
                    <mesh geometry={nodes.Object_10.geometry} material={carBodyColor} />
                    <mesh geometry={nodes.Object_11.geometry} material={carBodyColor} />
                    <mesh geometry={nodes.Object_12.geometry} material={materials.Doorrf0021Mtl} />
                    <mesh geometry={nodes.Object_13.geometry} material={materials.Doorrf0021Mtl} />
                    <mesh geometry={nodes.Object_14.geometry} material={materials.Doorrf0021Mtl} />
                    <mesh geometry={nodes.Object_15.geometry} material={materials.Doorrf0021Mtl} />
                    <mesh geometry={nodes.Object_16.geometry} material={interiorColor} />
                    <mesh geometry={nodes.Object_17.geometry} material={materials.Doorrf0051Mtl} />
                    <mesh geometry={nodes.Object_18.geometry} material={materials.Doorrf0061Mtl} />
                    <mesh geometry={nodes.Object_19.geometry} material={materials.Doorrf1Mtl} />
                    <mesh geometry={nodes.Object_20.geometry} material={materials.Fari0071Mtl} />
                    <mesh geometry={nodes.Object_21.geometry} material={materials.Wheel0011Mtl} />
                    <mesh geometry={nodes.Object_22.geometry} material={materials.Wheel0011Mtl} />
                    <mesh geometry={nodes.Object_23.geometry} material={materials.Wheel0011Mtl} />
                    <mesh geometry={nodes.Object_24.geometry} material={materials.Wheel0011Mtl} />
                    {rimType == 1 && <>
                        <mesh geometry={nodes.Object_25.geometry} material={rimColor} />
                        <mesh geometry={nodes.Object_26.geometry} material={rimColor} />
                        <mesh geometry={nodes.Object_27.geometry} material={rimColor} />
                        <mesh geometry={nodes.Object_28.geometry} material={rimColor} />
                        <mesh geometry={nodes.Object_29.geometry} material={materials.Wheel0031Mtl} />
                        <mesh geometry={nodes.Object_30.geometry} material={materials.Wheel0031Mtl} />
                        <mesh geometry={nodes.Object_31.geometry} material={materials.Wheel0031Mtl} />
                        <mesh geometry={nodes.Object_32.geometry} material={materials.Wheel0031Mtl} />
                    </>}
                    {/*  */}
                    {rimType == 2 && <>
                        <group position={[-24.53, 2.59, 1.6]} rotation={[0, 0, 0]} scale={4.5}>
                            <mesh geometry={nodes1.Object_7.geometry} material={rimColor} />
                            <mesh geometry={nodes1.Object_8.geometry} material={rimColor} />
                        </group>
                        <group position={[-24.53, 14.95, 1.6]} rotation={[0, 0, 0]} scale={4.5}>
                            <mesh geometry={nodes1.Object_7.geometry} material={rimColor} />
                            <mesh geometry={nodes1.Object_8.geometry} material={rimColor} />
                        </group>
                        <group position={[-32.65, 2.58, 1.6]} rotation={[0, 0, 3.12]} scale={4.5}>
                            <mesh geometry={nodes1.Object_7.geometry} material={rimColor} />
                            <mesh geometry={nodes1.Object_8.geometry} material={rimColor} />
                        </group>
                        <group position={[-32.65, 14.95, 1.6]} rotation={[0, 0, 3.12]} scale={4.5}>
                            <mesh geometry={nodes1.Object_7.geometry} material={rimColor} />
                            <mesh geometry={nodes1.Object_8.geometry} material={rimColor} />
                        </group>
                    </>}
                    {rimType == 3 && <>
                        <group position={[-24.63, 2.59, 1.6]} rotation={[0, 0, -1.57]} scale={0.093}>
                            <mesh geometry={nodes1.Object_4.geometry} material={rimColor} />
                            <mesh geometry={nodes1.Object_5.geometry} material={rimColor} />
                        </group>
                        <group position={[-24.63, 14.95, 1.6]} rotation={[0, 0, -1.57]} scale={0.093}>
                            <mesh geometry={nodes1.Object_4.geometry} material={rimColor} />
                            <mesh geometry={nodes1.Object_5.geometry} material={rimColor} />
                        </group>
                        <group position={[-32.6, 2.59, 1.6]} rotation={[0, 0, 1.57]} scale={0.093}>
                            <mesh geometry={nodes1.Object_4.geometry} material={rimColor} />
                            <mesh geometry={nodes1.Object_5.geometry} material={rimColor} />
                        </group>
                        <group position={[-32.6, 14.95, 1.6]} rotation={[0, 0, 1.57]} scale={0.093}>
                            <mesh geometry={nodes1.Object_4.geometry} material={rimColor} />
                            <mesh geometry={nodes1.Object_5.geometry} material={rimColor} />
                        </group>
                    </>}

                    <mesh geometry={nodes.Object_33.geometry} material={materials.Wheel0031Mtl} />
                    <mesh geometry={nodes.Object_34.geometry} material={materials.Wheel0041Mtl} />
                    <mesh geometry={nodes.Object_35.geometry} material={materials.Wheel1Mtl} />
                </group>
            </group>
        </group >
    )
}

useGLTF.preload('./models/lotusEmira.glb')
