/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 .\public\models\toyotaSupra.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useSelector } from 'react-redux';
import { MeshStandardMaterial } from 'three';

export function ToyotaSupra(props) {
    const cbc = useSelector((state) => state.carColors.carBodyColor);
    const inc = useSelector((state) => state.carColors.InteriorColor);
    const rim = useSelector((state) => state.carColors.rimColor);
    const rimType = useSelector((state) => state.carColors.rimType);
    const carBodyColor = new MeshStandardMaterial({ color: cbc });
    const interiorColor = new MeshStandardMaterial({ color: inc });
    const rimColor = new MeshStandardMaterial({ color: rim });
    const { nodes, materials } = useGLTF('./models/toyotaSupra.glb')
    const nodes1 = useGLTF('./models/wheelRims.glb').nodes

    return (
        <group {...props} dispose={null}>
            <group position={[0, -0.505, -0.115]} scale={0.806}>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={2.439}>
                    <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                        <group scale={0.342}>
                            <mesh geometry={nodes.Plane032_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane030_screen_0.geometry} material={materials.screen} />
                            <mesh geometry={nodes.Plane006_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane044_seat_0.geometry} material={interiorColor} />
                            <mesh geometry={nodes.Plane038_carbon_0.geometry} material={materials.carbon} />
                            <mesh geometry={nodes.Plane005_button_0.geometry} material={materials.button} />
                            <mesh geometry={nodes.Plane005_button_0_1.geometry} material={materials.button} />
                            <mesh geometry={nodes.Plane005_button_0_2.geometry} material={materials.button} />
                            <mesh geometry={nodes.Plane022_metal_0.geometry} material={materials.metal} />
                            <mesh geometry={nodes.Plane014_blackleather_0.geometry} material={materials.blackleather} />
                            <mesh geometry={nodes.Plane058_screen_0.geometry} material={materials.screen} />
                            <mesh geometry={nodes.Plane002_metal_0.geometry} material={materials.metal} />
                            <mesh geometry={nodes.Plane002_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane007_blackleather_0.geometry} material={materials.blackleather} />
                            <mesh geometry={nodes.Plane042_blackleather_0.geometry} material={interiorColor} />
                            <mesh geometry={nodes.Plane009_metal_0.geometry} material={materials.metal} />
                            <mesh geometry={nodes.Plane039_lambert1_0.geometry} material={materials.lambert1} />
                            <mesh geometry={nodes.Plane043_metal_0.geometry} material={materials.metal} />
                            <mesh geometry={nodes.Plane052_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane016_tire_0.geometry} material={materials.tire} />
                            <mesh geometry={nodes.Plane016_metal_0.geometry} material={materials.metal} />
                            <mesh geometry={nodes.Plane016_lambert1_0.geometry} material={materials.lambert1} />

                            {rimType == 1 && <mesh geometry={nodes.Plane016_GlossBlackpaint_0.geometry} material={rimColor} />}
                            {rimType == 2 && <group position={[-107, 39, 164.5]} rotation={[1.5, 0, 3.15]} scale={110}>
                                <mesh geometry={nodes1.Object_7.geometry} material={rimColor} />
                                <mesh geometry={nodes1.Object_8.geometry} material={rimColor} />
                            </group>}
                            {rimType == 3 && <group position={[-105, 39, 164]} rotation={[1.5, 0.01, 1.55]} scale={2.2}>
                                <mesh geometry={nodes1.Object_4.geometry} material={rimColor} />
                                <mesh geometry={nodes1.Object_5.geometry} material={rimColor} />
                            </group>}


                            <mesh geometry={nodes.Plane016_blackplate_metal_0.geometry} material={materials.blackplate_metal} />
                            <mesh geometry={nodes.Plane046_mirror_0.geometry} material={materials.mirror} />
                            <mesh geometry={nodes.Plane037_balck_tint_glass_0.geometry} material={materials.balck_tint_glass} />
                            <mesh geometry={nodes.Plane040_lambert1_0.geometry} material={materials.lambert1} />
                            <mesh geometry={nodes.Plane069_brake_0.geometry} material={materials.brake} />
                            <mesh geometry={nodes.Plane050_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane041_lambert1_0.geometry} material={materials.lambert1} />
                            <mesh geometry={nodes.Plane027_orange_light_0.geometry} material={materials.orange_light} />
                            <mesh geometry={nodes.Plane010_balck_tint_glass_0.geometry} material={materials.balck_tint_glass} />
                            <mesh geometry={nodes.Plane023_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane008_brake_0.geometry} material={materials.brake} />
                            <mesh geometry={nodes.Plane019_brake_0.geometry} material={materials.brake} />
                            <mesh geometry={nodes.Plane056_taillights_0.geometry} material={materials.taillights} />
                            <mesh geometry={nodes.Plane020_tire_0.geometry} material={materials.tire} />
                            <mesh geometry={nodes.Plane020_metal_0.geometry} material={materials.metal} />
                            <mesh geometry={nodes.Plane020_lambert1_0.geometry} material={materials.lambert1} />

                            {rimType == 1 && <mesh geometry={nodes.Plane020_GlossBlackpaint_0.geometry} material={rimColor} />}
                            {rimType == 2 && <group position={[-109, 39.5, -131]} rotation={[1.5, 0, 3.15]} scale={110}>
                                <mesh geometry={nodes1.Object_7.geometry} material={rimColor} />
                                <mesh geometry={nodes1.Object_8.geometry} material={rimColor} />
                            </group>}
                            {rimType == 3 && <group position={[-106, 40, -130]} rotation={[1.5, 0.01, 1.55]} scale={2.2}>
                                <mesh geometry={nodes1.Object_4.geometry} material={rimColor} />
                                <mesh geometry={nodes1.Object_5.geometry} material={rimColor} />
                            </group>}
                            <mesh geometry={nodes.Plane029_light_0.geometry} material={materials.light} />
                            <mesh geometry={nodes.Plane_lambert1_0.geometry} material={materials.lambert1} />
                            <mesh geometry={nodes.Plane017_brake_0.geometry} material={materials.brake} />
                            <mesh geometry={nodes.Plane034_seat_0.geometry} material={materials.seat} />
                            <mesh geometry={nodes.Plane048_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane015_brake_0.geometry} material={materials.brake} />
                            <mesh geometry={nodes.Plane033_blackleather_0.geometry} material={materials.blackleather} />
                            <mesh geometry={nodes.Plane047_carpaint_0.geometry} material={new MeshStandardMaterial({ color: '#000000' })} />
                            <mesh geometry={nodes.Plane051_carplate_0.geometry} material={materials.carplate} />
                            <mesh geometry={nodes.Plane051_blackplate_metal_0.geometry} material={materials.blackplate_metal} />
                            <mesh geometry={nodes.Plane018_tire_0.geometry} material={materials.tire} />
                            <mesh geometry={nodes.Plane018_metal_0.geometry} material={materials.metal} />
                            <mesh geometry={nodes.Plane018_lambert1_0.geometry} material={materials.lambert1} />

                            {rimType == 1 && <mesh geometry={nodes.Plane018_GlossBlackpaint_0.geometry} material={rimColor} />}
                            {rimType == 2 && <group position={[109, 39.5, -131]} rotation={[1.5, 0, 0]} scale={110}>
                                <mesh geometry={nodes1.Object_7.geometry} material={rimColor} />
                                <mesh geometry={nodes1.Object_8.geometry} material={rimColor} />
                            </group>}
                            {rimType == 3 && <group position={[106, 40, -130]} rotation={[1.5, 0.01, -1.55]} scale={2.2}>
                                <mesh geometry={nodes1.Object_4.geometry} material={rimColor} />
                                <mesh geometry={nodes1.Object_5.geometry} material={rimColor} />
                            </group>}
                            <mesh geometry={nodes.Plane018_blackplate_metal_0.geometry} material={materials.blackplate_metal} />
                            <mesh geometry={nodes.Plane004_carpaint_0.geometry} material={carBodyColor} />
                            <mesh geometry={nodes.Plane004_carpaint_0_1.geometry} material={carBodyColor} />
                            <mesh geometry={nodes.Plane004_carbon_0.geometry} material={materials.carbon} />
                            <mesh geometry={nodes.Plane004_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane036_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane003_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane045_orange_light_0.geometry} material={materials.orange_light} />
                            <mesh geometry={nodes.Plane025_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane001_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane001_GlossBlackpaint_0_1.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane035_balck_tint_glass_0.geometry} material={materials.balck_tint_glass} />
                            <mesh geometry={nodes.Plane074_tire_0.geometry} material={materials.tire} />
                            <mesh geometry={nodes.Plane074_metal_0.geometry} material={materials.metal} />
                            <mesh geometry={nodes.Plane074_lambert1_0.geometry} material={materials.lambert1} />

                            {rimType == 1 && <mesh geometry={nodes.Plane074_GlossBlackpaint_0.geometry} material={rimColor} />}
                            {rimType == 2 && <group position={[107, 39.5, 164.5]} rotation={[1.5, 0, 0]} scale={110}>
                                <mesh geometry={nodes1.Object_7.geometry} material={rimColor} />
                                <mesh geometry={nodes1.Object_8.geometry} material={rimColor} />
                            </group>}
                            {rimType == 3 && <group position={[105, 40, 164]} rotation={[1.5, 0.01, -1.55]} scale={2.2}>
                                <mesh geometry={nodes1.Object_4.geometry} material={rimColor} />
                                <mesh geometry={nodes1.Object_5.geometry} material={rimColor} />
                            </group>}
                            <mesh geometry={nodes.Plane074_blackplate_metal_0.geometry} material={materials.blackplate_metal} />
                            <mesh geometry={nodes.Plane026_light_0.geometry} material={materials.light} />
                            <mesh geometry={nodes.Plane031_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane054_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane013_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane055_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane060_GlossBlackpaint_0.geometry} material={materials.GlossBlackpaint} />
                            <mesh geometry={nodes.Plane049_blackleather_0.geometry} material={materials.blackleather} />
                            <mesh geometry={nodes.Plane011_blackleather_0.geometry} material={materials.blackleather} />
                            <mesh geometry={nodes.Plane012_red_reflec_0.geometry} material={materials.red_reflec} />
                            <mesh geometry={nodes.Plane024_blackleather_0.geometry} material={materials.blackleather} />
                            <mesh geometry={nodes.Plane021_mirror_0.geometry} material={materials.mirror} />
                            <mesh geometry={nodes.Plane076_light_0.geometry} material={materials.light} />
                            <mesh geometry={nodes.Plane077_light_0.geometry} material={materials.light} />
                            <mesh geometry={nodes.Plane078_light_0.geometry} material={materials.light} />
                        </group>
                        <mesh geometry={nodes.pDisc1_light_0.geometry} material={materials.light} />
                        <mesh geometry={nodes.pDisc4_light_0.geometry} material={materials.light} />
                    </group>
                </group>
            </group>
        </group>
    )
}
useGLTF.preload('./models/wheelRims.glb')

useGLTF.preload('./models/toyotaSupra.glb')
